name: portfolioapp

services:
  backend:
    build:
      context: ../../services/backend
    volumes:
      - ../../services/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ../../services/frontend
    volumes:
      - ../../services/frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
