name: portfolioapp-stage

services:
  nginx:
    image: ${NGINX_IMAGE}:${TAG}
    container_name: nginx-stage
    ports:
      - "8081:80" # Accessible via Tailscale only
    depends_on:
      - backend
      - frontend
    networks:
      - app_net_stage
    restart: unless-stopped

  backend:
    image: ${BACKEND_IMAGE}:${TAG}
    container_name: backend-stage
    env_file:
      - ../env/.env.stage
    expose:
      - "8000"
    networks:
      - app_net_stage
    restart: unless-stopped

  frontend:
    image: ${FRONTEND_IMAGE}:${TAG}
    container_name: frontend-stage
    env_file:
      - ../env/.env.stage
    expose:
      - "3000"
    networks:
      - app_net_stage
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres-stage
    restart: unless-stopped

    env_file:
      - ../env/.env.stage

    volumes:
      - postgres_data_stage:/var/lib/postgresql/data

    networks:
      - app_net_stage

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: ${BACKEND_IMAGE}:${TAG}
    command: uv run alembic upgrade head
    container_name: migrate-stage
    env_file: ../env/.env.stage
    networks:
      - app_net_stage
    depends_on:
      - postgres

volumes:
  postgres_data_stage:

networks:
  app_net_stage:
    driver: bridge
