name: portfolioapp-prod

services:
  nginx:
    image: ${NGINX_IMAGE}:${TAG}
    container_name: nginx-prod
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_net_prod

  backend:
    image: ${BACKEND_IMAGE}:${TAG}
    container_name: backend-prod
    env_file:
      - ../env/.env.prod
    expose:
      - "8000"
    networks:
      - app_net_prod

  frontend:
    image: ${FRONTEND_IMAGE}:${TAG}
    container_name: frontend-prod
    env_file:
      - ../env/.env.prod
    environment:
      NODE_ENV: production
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app_net_prod

  postgres:
    image: postgres:16-alpine
    container_name: postgres-prod
    restart: unless-stopped

    env_file:
      - ../env/.env.prod

    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

    networks:
      - app_net_prod

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: ${BACKEND_IMAGE}:${TAG}
    command: uv run alembic upgrade head
    container_name: migrate-prod
    env_file: ../env/.env.prod
    networks:
      - app_net_prod
    depends_on:
      - postgres

volumes:
  postgres_data_prod:

networks:
  app_net_prod:
    driver: bridge
