name: portfolioapp-prod

services:
  nginx:
    image: ${NGINX_IMAGE}:${TAG}
    container_name: nginx-prod
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app_net_prod

  backend:
    image: ${BACKEND_IMAGE}:${TAG}
    container_name: backend-prod
    expose:
      - "8000"
    networks:
      - app_net_prod
  
  frontend:
    image: ${FRONTEND_IMAGE}:${TAG}
    container_name: frontend-prod
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - app_net_prod

networks:
  app_net_prod:
    driver: bridge
